include "confs/oneshot.conf"

dataset {
    with_projection = True
    consistent_images = True
    consistent_projectors = True
    consistent_proj_noise = False
}

model {
    projection_network {
        mode = original
        d_feature = 256
        d_hidden = 256
        n_layers = 3
        weight_norm = True
        multires_view = 8
        encoding_view = default
        pattern_offset_size = [32,24]
    }
}